### ISSUE TITLE
TypeError: Cannot call method 'join' of undefined, when initializing project

### ISSUE THREAD

**Issue by zenlambda** [cmackay/hybrid-boilerplate#2]
I followed the steps in the README up to 'gulp init' and got the following error:

```
» gulp init
[11:41:37] Using gulpfile ~/Desktop/hybrid-boilerplate/gulpfile.js
[11:41:37] Starting 'init'...
? Are you sure you want to initialize the project: Yes
? Enter the project name: (hybrid-boilerplate) fooapp



/Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/node_modules/rx/dist/rx.js:580
    throw e;
          ^
TypeError: Cannot call method 'join' of undefined
    at Object.inquirer.prompt.validate (/Users/frank/Desktop/hybrid-boilerplate/config/gulp/tasks/init.js:79:28)
    at Object.utils.runAsync (/Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/lib/utils/utils.js:29:22)
    at /Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/lib/prompts/base.js:151:13
    at tryCatcher (/Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/node_modules/rx/dist/rx.js:568:29)
    at setDisposable [as action] (/Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/node_modules/rx/dist/rx.js:4831:36)
    at ScheduledItem.invokeCore (/Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/node_modules/rx/dist/rx.js:927:17)
    at ScheduledItem.invoke (/Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/node_modules/rx/dist/rx.js:915:40)
    at runTrampoline (/Users/frank/Desktop/hybrid-boilerplate/node_modules/inquirer/node_modules/rx/dist/rx.js:1236:39)
    at tryCatc%
```

**Comment by cmackay** [comment]
@zenlambda Thanks for submitting this issue. It looks like the api changed for the validate-npm-package-name dependency. I will have a fix submitted in a few minutes.

Thanks!

-Craig
